### ISSUE TITLE
Use case question: Is this useful if I have Odin?

### ISSUE THREAD

**Issue by JesseTG** [pschraut/UnityPlayModeInspector#2]
I'm considering toying around with this library, but before I do I must ask; do I need to, really? If I bought Odin Inspector, can I do anything with UnityPlayModeInspector that I can't easily do with Odin? I'm not knocking you or your efforts, I'm just trying to understand the use case of this library.

**Comment by pschraut** [comment]
I don't know what you can do with Odin, so I can't answer your question. Most of the time I use PlayMode Inspector to:

- Visualize non-serialized private data of any type
- Visualize static data of any type
- Add debug/cheats functionality

In PlayMode Inspector you write your own visualization code, which allows you to do everything you can think of. There are no "building blocks" you can pick from. If you can do it with EditorGUI, you can do it with PlayMode Inspector. That's why it's so useful.

**Comment by JesseTG** [comment]
Fair enough. Thanks for the clarification!
